[package]
name = "ultimate_character"
version = "0.0.1"
edition = "2024"

[dependencies]
jiff = "0.2.5"
serenity = "0.12.4"
ulid = "1.2.1"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
