[package]
name = "ultimate_character"
version = "0.0.12"
edition = "2024"

[dependencies]
bon = "3.6.3"
jiff = { version = "0.2.14", features = ["serde"] }
poise = { git = "https://github.com/serenity-rs/poise.git", branch = "next" }
serde = { version = "1.0.219", features = ["derive"] }
ulid = { version = "1.2.1", features = ["serde"] }
ultimate_config = { path = "../ultimate_config" }
ultimate_phrases = { path = "../ultimate_phrases" }
ultimate_modals = { path = "../ultimate_modals" }
url = "2.5.4"
surrealdb = "2.3.3"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
