[package]
name = "ultimate_modals"
version = "0.0.2"
edition = "2024"

[dependencies]
poise = { git = "https://github.com/serenity-rs/poise.git", branch = "next" }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
