[package]
name = "ultimate_message"
version = "0.0.3"
edition = "2024"

[dependencies]
async-openai = "0.28.0"
serenity = "0.12.4"
ultimate_config = { path = "../ultimate_config" }
ultimate_character = { path = "../ultimate_character" }
snafu = "0.8.5"
jiff = { version = "0.2.5", features = ["serde"] }
ulid = "1.2.1"
serde = { version = "1.0.219", features = ["derive"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
missing-errors-doc = "allow"                 # TODO: remove
enum_glob_use = "deny"
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
