[package]
name = "ultimate_message"
version = "0.0.5"
edition = "2024"

[dependencies]
async-openai = { version = "0.33.1", features = [
  "_api",
  "chat-completion-types",
] }
serenity = { git = "https://github.com/serenity-rs/serenity.git", branch = "next" }
ultimate_config = { path = "../ultimate_config" }
ultimate_character = { path = "../ultimate_character" }
snafu = "0.9.0"
jiff = { version = "0.2.23", features = ["serde"] }
ulid = "1.2.1"
serde = { version = "1.0.228", features = ["derive"] }
surrealdb = "2.6.3"
bon = "3.9.1"
nonempty = { version = "0.12.0", features = ["serialize"] }
miette = "7.6.0"
ureq = "3.2.0"
base64 = "0.22.1"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
