[package]
name = "ultimate_phrases"
version = "0.0.3"
edition = "2024"

[dependencies]
nanorand = "0.7.0"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
missing-errors-doc = "allow"                 # TODO: remove
enum_glob_use = "deny"
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
