use std::collections::{HashMap, HashSet};

use jiff::Zoned;
use serenity::all::UserId;
use ulid::Ulid;

/// A character.
pub struct Character {
    /// The character's name.
    name: String,
    /// A short description of the character.
    ///
    /// This is not read by the model, it is only used for display purposes.
    description: Option<String>,
    /// The character's personality.
    ///
    /// This should be a first-person description of the character.
    ///
    /// This is read by the model, as a guide on how to act.
    personality: Option<String>,
    /// The character's greeting.
    ///
    /// This is the first message in every conversation.
    greeting: String,
    /// The character's unique ID, generated on creation.
    id: Ulid,
    /// The character's avatar's URL.
    ///
    /// Note: Do not set this to the link of an uploaded image on Discord,
    /// as those are temporary. Instead, prefer a link to an image on a
    /// permanent host, such as a CDN or a public image host.
    avatar: Option<String>,
    /// The character's emoji. Usually displayed before the character's name.
    ///
    /// Although this is called "emoji", it actually being an emoji is never
    /// enforced.
    emoji: Option<String>,
    /// The Discord user ID of the character's original creator.
    creator: UserId,
    /// The Discord user IDs of everyone who has edited the character, if any.
    editors: HashSet<UserId>,
    /// The current version of the character.
    ///
    /// This starts at 0 and increments by 1 with each edit.
    version: u32,
    /// The hex color of the character.
    color: Option<String>,
    /// The time the character was created.
    created_at: Zoned,
    /// The times the character was edited.
    edited_at: Vec<Zoned>,
    /// The latest time the character had a conversation with a user.
    latest_conversation: Option<Zoned>,
    /// The number of conversations the character has had with a user.
    ///
    /// This means the amount of times this character has been "spawned".
    conversations_had_with_user: HashMap<UserId, u32>,
    /// The number of conversations the character has had.
    ///
    /// This means the amount of times this character has been "spawned".
    conversations_had: u32,
    /// The number of words generated by the character.
    words_generated: u32,
    /// The number of tokens generated by the character.
    tokens_generated: u32,
    /// The example messages for the character.
    ///
    /// Setting example messages are a great way to teach the character how to
    /// act.
    ///
    /// The first element of the tuple is optionally a user's message, and the
    /// second is the character's response to that message.
    example_messages: Vec<(Option<String>, String)>,
    /// The system prompt, always placed as the latest message.
    system_prompt: Option<String>,
    /// The prompt for the character.
    ///
    /// This should be a list of instructions for how the character should
    /// behave.
    prompt: Option<String>,
    /// The scenario for the character.
    ///
    /// This is meant as the scene, setting, or location that the character
    /// starts in.
    scenario: Option<String>,
    /// The frequency penalty for the character.
    ///
    /// If set, this overrides the default frequency penalty for requests.
    frequency_penalty: Option<f32>,
    /// The presence penalty for the character.
    ///
    /// If set, this overrides the default presence penalty for requests.
    presence_penalty: Option<f32>,
    /// The temperature for the character.
    ///
    /// If set, this overrides the default temperature for requests.
    temperature: Option<f32>,
    /// The top-p value for the character.
    ///
    /// If set, this overrides the default top-p value for requests.
    top_p: Option<f32>,
    /// The previous versions of the character.
    ///
    /// This is used for rollback purposes.
    previous_versions: HashMap<u32, Character>,
}

impl Character {
    #[must_use]
    pub fn new(
        name: String,
        description: Option<String>,
        personality: Option<String>,
        greeting: String,
        avatar: Option<String>,
        emoji: Option<String>,
        creator: UserId,
        color: Option<String>,
        example_messages: Vec<(Option<String>, String)>,
        system_prompt: Option<String>,
        prompt: Option<String>,
        scenario: Option<String>,
        frequency_penalty: Option<f32>,
        presence_penalty: Option<f32>,
        temperature: Option<f32>,
        top_p: Option<f32>,
    ) -> Self {
        let id = Ulid::new();
        let editors = HashSet::new();
        let version = 1;
        let created_at = Zoned::now();
        let edited_at = vec![];
        let latest_conversation = None;
        let conversations_had_with_user = HashMap::new();
        let conversations_had = 0;
        let words_generated = 0;
        let tokens_generated = 0;
        let previous_versions = HashMap::new();
        Self {
            name,
            description,
            personality,
            greeting,
            id,
            avatar,
            emoji,
            creator,
            editors,
            version,
            color,
            created_at,
            edited_at,
            latest_conversation,
            conversations_had_with_user,
            conversations_had,
            words_generated,
            tokens_generated,
            example_messages,
            system_prompt,
            prompt,
            scenario,
            frequency_penalty,
            presence_penalty,
            temperature,
            top_p,
            previous_versions,
        }
    }
}
