[package]
name = "ultimate_history"
version = "0.0.4"
edition = "2024"

[dependencies]
ultimate_message = { path = "../ultimate_message" }
ultimate_character = { path = "../ultimate_character" }
serenity = "0.12.4"
ulid = "1.2.1"
ron = "0.10.1"
snafu = "0.8.5"
serde = { version = "1.0.219", features = ["derive"] }
tracing = "0.1.41"
async-openai = "0.28.1"
dashmap = { version = "6.1.0", features = ["serde"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
missing-errors-doc = "allow"                 # TODO: remove
enum_glob_use = "deny"
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
