[package]
name = "ultimate_history"
version = "0.0.8"
edition = "2024"

[dependencies]
ultimate_message = { path = "../ultimate_message" }
ultimate_character = { path = "../ultimate_character" }
ultimate_config = { path = "../ultimate_config" }
serenity = { git = "https://github.com/serenity-rs/serenity.git", branch = "next" }
snafu = "0.9.0"
serde = { version = "1.0.228", features = ["derive"] }
async-openai = "0.33.1"
surrealdb = "2.6.3"
nonempty = { version = "0.12.0", features = ["serialize"] }
bon = "3.9.1"
poise = { git = "https://github.com/serenity-rs/poise.git", branch = "serenity-next" }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
