[package]
name = "ultimate_history"
version = "0.0.2"
edition = "2024"

[dependencies]
ultimate_message = { path = "../ultimate_message" }
ultimate_character = { path = "../ultimate_character" }
serenity = "0.12.4"
ulid = "1.2.1"
parking_lot = "0.12.3"
ron = "0.9.0"
snafu = "0.8.5"
serde = { version = "1.0.219", features = ["derive"] }
tracing = "0.1.41"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
missing-errors-doc = "allow"                 # TODO: remove
enum_glob_use = "deny"
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
