[package]
name = "ultimate_database"
version = "0.0.3"
edition = "2024"

[dependencies]
miette = "7.6.0"
serde = { version = "1.0.219", features = ["derive"] }
serenity = "0.12.4"
snafu = "0.8.5"
surrealdb = { version = "2.3.3", features = ["kv-surrealkv"] }
ultimate_character = { path = "../ultimate_character" }
ultimate_message = { path = "../ultimate_message" }
ultimate_history = { path = "../ultimate_history" }
bon = "3.6.3"
tokio = "1.45.1"
jiff = "0.2.14"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
