[package]
name = "ultimate_database"
version = "0.0.3"
edition = "2024"

[dependencies]
miette = "7.6.0"
serde = { version = "1.0.228", features = ["derive"] }
serenity = { git = "https://github.com/serenity-rs/serenity.git", branch = "next" }
snafu = "0.9.0"
surrealdb = { version = "2.6.3", features = ["kv-surrealkv"] }
ultimate_character = { path = "../ultimate_character" }
ultimate_message = { path = "../ultimate_message" }
ultimate_history = { path = "../ultimate_history" }
bon = "3.9.1"
tokio = "1.50.0"
jiff = "0.2.23"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
