use bon::Builder;
use jiff::Zoned;
use poise::serenity_prelude::{
    CreateComponent, CreateInteractionResponse, CreateInteractionResponseMessage, MessageId,
    all::{
        ButtonStyle, Color, CreateActionRow, CreateButton, CreateEmbed, CreateEmbedFooter, UserId,
    },
};
use serde::{Deserialize, Serialize};
use std::{
    collections::{HashMap, HashSet},
    fmt::{Display, Write as _},
};
use surrealdb::RecordId;
use ulid::Ulid;
use url::Url;

use crate::{
    constants::{NO_PHRASES, YES_PHRASES, sample},
    db::Database,
    llm::ModelSettings,
    models::modals::{
        CreateCharacterModal, EditCharacterModal, SecondCreateCharacterModal,
        SecondEditCharacterModal,
    },
};

/// e.g. 16 May, Friday, 2025 | 17:41:14 | 2025-05-16
/// [jiff::fmt::strtime](https://docs.rs/jiff/latest/jiff/fmt/strtime/index.html)
const GOOD_DATE_FORMAT: &str = "%e %B, %A, %G | %T | %F";

/// A character.
#[derive(Debug, Clone, Serialize, Deserialize, Builder)]
pub struct Character {
    /// The character's name.
    #[builder(into)]
    name: String,
    /// The character's greeting.
    ///
    /// This is the first message in every conversation.
    #[builder(into)]
    greeting: String,
    /// The character's unique ID, generated on creation.
    id: RecordId,
    /// The Discord user ID of the character's original creator.
    #[builder(into)]
    creator: UserId,
    /// The current version of the character.
    ///
    /// This starts at 0 and increments by 1 with each edit.
    #[builder(default)]
    version: u32,
    /// The ID of the next version of the character.
    ///
    /// If Some, the character will no longer be visible.
    next_version: Option<RecordId>,
    /// The ID of the previous version of the character.
    ///
    /// This is used for rollback purposes.
    previous_version: Option<RecordId>,
    /// The character's nickname.
    ///
    /// This is intented to be a short version of the name, to
    /// more easily start conversations with the character.
    nickname: Option<String>,
    /// A short description of the character.
    ///
    /// This is not read by the model, it is only used for display purposes.
    description: Option<String>,
    /// The character's personality.
    ///
    /// This should be a first-person description of the character.
    ///
    /// This is read by the model, as a guide on how to act.
    personality: Option<String>,
    /// The prompt for the character.
    ///
    /// This should be a list of instructions for how the character should
    /// behave.
    prompt: Option<String>,
    /// The system prompt, always placed as the latest message.
    system_prompt: Option<String>,
    /// The scenario for the character.
    ///
    /// This is meant as the scene, setting, or location that the character
    /// starts in.
    scenario: Option<String>,
    /// The character's avatar's URL.
    ///
    /// Note: Do not set this to the link of an uploaded image on Discord,
    /// as those are temporary. Instead, prefer a link to an image on a
    /// permanent host, such as a CDN or a public image host.
    avatar: Option<String>,
    /// The character's emoji. Usually displayed before the character's name.
    ///
    /// Although this is called "emoji", it actually being an emoji is never
    /// enforced.
    emoji: Option<String>,
    /// The Discord user IDs of anyone who has ever edited the character, if any.
    #[builder(default)]
    all_editors: HashSet<UserId>,
    /// The Discord user ID of the latest person to edit the character, if any.
    latest_editor: Option<UserId>,
    /// If Some, the Discord user ID of the character's deleter.
    ///
    /// If Some, the character will no longer be visible.
    deleted_by: Option<UserId>,
    /// The hex color of the character.
    color: Option<Color>,
    /// The time the character was created.
    #[builder(default = Zoned::now())]
    created_at: Zoned,
    /// If Some, the time this version was created.
    edited_at: Option<Zoned>,
    /// If Some, the time the character was deleted.
    deleted_at: Option<Zoned>,
    /// The latest time the character had a conversation with a user.
    latest_conversation: Option<Zoned>,
    /// The number of conversations the character has had with a user.
    ///
    /// This means the amount of times this character has been "spawned".
    #[builder(default)]
    conversations_had_with_user: HashMap<UserId, u32>,
    /// The number of conversations the character has had.
    ///
    /// This means the amount of times this character has been "spawned".
    #[builder(default)]
    conversations_had: u32,
    /// The number of words generated by the character.
    #[builder(default)]
    words_generated: u32,
    /// The number of tokens generated by the character.
    #[builder(default)]
    tokens_generated: u32,
    /// The example messages for the character.
    ///
    /// Setting example messages are a great way to teach the character how to
    /// act.
    ///
    /// The first element of the tuple is optionally a user's message, and the
    /// second is the character's response to that message.
    #[builder(default)]
    example_messages: Vec<(Option<String>, String)>,
    /// The model settings override for the character.
    ///
    /// If set, this overrides the default model settings for requests.
    model_settings: Option<ModelSettings>,
    /// The similarity of the character to the input.
    ///
    /// This is `Some` when the user searches a character by name, e.g. `chat` or `delete`. and `None` in e.g. `view`.
    similarity: Option<f64>,
}

#[derive(Debug, Serialize, Deserialize, Builder)]
pub struct CharacterPages {
    #[builder(with = |id: MessageId| RecordId::from(("character_page", id.to_string())))]
    id: RecordId,
    #[builder(with = |cs: &[Character]| cs.iter().map(Character::id).cloned().collect())]
    characters: Vec<RecordId>,
    #[builder(default)]
    current_page: usize,
    /// `Some` if the user entered a name when running the command.
    ///
    /// This is then used to display the similarity of the names.
    name: Option<String>,
}

impl Character {
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    #[must_use]
    pub fn greeting(&self) -> &str {
        &self.greeting
    }

    #[must_use]
    pub fn personality(&self) -> Option<&str> {
        self.personality.as_deref()
    }

    #[must_use]
    pub fn prompt(&self) -> Option<&str> {
        self.prompt.as_deref()
    }

    #[must_use]
    pub fn system_prompt(&self) -> Option<&str> {
        self.system_prompt.as_deref()
    }

    #[must_use]
    pub fn scenario(&self) -> Option<&str> {
        self.scenario.as_deref()
    }

    #[must_use]
    pub const fn example_messages(&self) -> &[(Option<String>, String)] {
        self.example_messages.as_slice()
    }

    #[must_use]
    pub fn avatar(&self) -> Option<&str> {
        self.avatar.as_deref()
    }

    #[must_use]
    pub const fn color(&self) -> Option<Color> {
        self.color
    }

    #[must_use]
    pub const fn id(&self) -> &RecordId {
        &self.id
    }

    #[must_use]
    pub const fn conversations_had(&self) -> u32 {
        self.conversations_had
    }

    #[must_use]
    pub async fn formatted_conversations_had(&self, db: &Database) -> String {
        let mut string = format!("Totalt: {}", self.conversations_had);
        for (user, count) in &self.conversations_had_with_user {
            let user = db.substitute_name(user).await;
            let _ = write!(string, "\nMed {user}: {count}");
        }
        string
    }

    #[must_use]
    pub fn model_settings(&self) -> Option<ModelSettings> {
        self.model_settings.clone()
    }

    /// Returns e.g. ` | 75% namnlikhet` if `Some(0.75)`, otherwise returns an empty String.
    #[must_use]
    pub fn similarity(&self) -> String {
        self.similarity.map_or_else(String::new, |similarity| {
            format!(" | {:.0}% namnlikhet", similarity * 100.0)
        })
    }

    pub fn edit_from_modals(
        &mut self,
        editor: impl Into<UserId>,
        modal: EditCharacterModal,
        second_modal: SecondEditCharacterModal,
    ) {
        let editor = editor.into();
        self.latest_editor = Some(editor);
        self.all_editors.insert(editor);
        self.edited_at = Some(Zoned::now());
        self.version += 1;
        self.previous_version = Some(self.id.clone());
        self.id = RecordId::from(("character", Ulid::new().to_string()));
        let avatar = validate_url(second_modal.avatar);
        // the reason why these can't just be `self.foo = bar` is because
        // if the user doesn't fill in a field, it will be None, and we
        // don't want to overwrite a potentially existing value
        if let Some(name) = modal.name {
            self.name = name;
        }
        if let Some(greeting) = modal.greeting {
            self.greeting = greeting;
        }
        if let Some(nickname) = modal.nickname {
            self.nickname = Some(nickname);
        }
        if let Some(description) = modal.description {
            self.description = Some(description);
        }
        if let Some(personality) = modal.personality {
            self.personality = Some(personality);
        }
        if let Some(avatar) = avatar {
            self.avatar = Some(avatar);
        }
        if let Some(emoji) = second_modal.emoji {
            self.emoji = Some(emoji);
        }
        if let Some(system_prompt) = second_modal.system_prompt {
            self.system_prompt = Some(system_prompt);
        }
        if let Some(prompt) = second_modal.prompt {
            self.prompt = Some(prompt);
        }
        if let Some(scenario) = second_modal.scenario {
            self.scenario = Some(scenario);
        }
    }

    pub async fn into_embed_with_footer_text(
        self,
        footer_text: impl Into<String>,
        db: &Database,
    ) -> CreateEmbed<'static> {
        let mut embed = CreateEmbed::new()
            .title(self.to_string())
            .field("Hälsning", self.greeting.clone(), true)
            .field(
                "Konversationer",
                self.formatted_conversations_had(db).await,
                true,
            )
            .field("Version", (self.version + 1).to_string(), true);

        if let Some(nickname) = self.nickname.clone() {
            embed = embed.field("Smeknamn", nickname, true);
        }

        if let Some(personality) = self.personality.clone() {
            embed = embed.field("Personlighet", personality, true);
        }

        if let Some(prompt) = self.prompt.clone() {
            embed = embed.field("Prompt", prompt, true);
        }

        if let Some(system_prompt) = self.system_prompt.clone() {
            embed = embed.field("System Prompt", system_prompt, true);
        }

        if let Some(scenario) = self.scenario.clone() {
            embed = embed.field("Scenario", scenario, true);
        }

        embed = embed.field("Skapare", db.substitute_name(self.creator).await, true);

        if let Some(editor) = &self.latest_editor {
            let editor = db.substitute_name(editor).await;
            embed = embed.field("Redigerare", editor, true);
        }

        embed = embed.field(
            "Skapad",
            self.created_at.strftime(GOOD_DATE_FORMAT).to_string(),
            false,
        );
        if let Some(edited) = &self.edited_at {
            let edited = edited.strftime(GOOD_DATE_FORMAT).to_string();
            embed = embed.field("Redigerad", edited, false);
        }
        embed = embed
            .field("ID", self.id.key().to_string(), false)
            .footer(CreateEmbedFooter::new(footer_text.into()));

        if let Some(avatar) = self.avatar.clone() {
            embed = embed.thumbnail(avatar);
        }
        if let Some(color) = &self.color {
            embed = embed.color(*color);
        }
        if let Some(description) = self.description {
            embed = embed.description(description);
        }
        // TODO: previous/next buttons
        embed
    }

    #[must_use]
    pub fn to_confirm_interaction_response(
        id: impl Into<u64>,
        content: impl Into<String>,
    ) -> CreateInteractionResponse<'static> {
        let buttons = create_confirm_buttons(id);
        CreateInteractionResponse::UpdateMessage(
            CreateInteractionResponseMessage::new()
                .content(content.into())
                .components(buttons),
        )
    }
}

impl CharacterPages {
    #[must_use]
    pub fn id(&self) -> RecordId {
        self.id.clone()
    }
}

impl From<(CreateCharacterModal, SecondCreateCharacterModal, UserId)> for Character {
    fn from(
        (first, second, creator): (CreateCharacterModal, SecondCreateCharacterModal, UserId),
    ) -> Self {
        let avatar = validate_url(second.avatar);
        Self::builder()
            .name(first.name)
            .greeting(first.greeting)
            .id(RecordId::from(("character", Ulid::new().to_string())))
            .maybe_nickname(first.nickname)
            .maybe_description(first.description)
            .maybe_personality(first.personality)
            .maybe_avatar(avatar)
            .maybe_emoji(second.emoji)
            .creator(creator)
            .maybe_system_prompt(second.system_prompt)
            .maybe_prompt(second.prompt)
            .maybe_scenario(second.scenario)
            .build()
    }
}

impl Display for Character {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if let Some(emoji) = &self.emoji {
            write!(f, "{emoji} ")?;
        }
        write!(f, "{}", self.name())
    }
}

fn validate_url(url: Option<String>) -> Option<String> {
    url.and_then(|url| Url::parse(&url).ok())
        .filter(|url| matches!(url.scheme(), "https" | "http"))
        .map(|url| url.to_string())
}

fn create_confirm_buttons(id: impl Into<u64>) -> Vec<CreateComponent<'static>> {
    let id = id.into();
    let confirm_id = format!("{id}confirm");
    let cancel_id = format!("{id}cancel");
    vec![CreateComponent::ActionRow(CreateActionRow::Buttons(
        vec![
            CreateButton::new(confirm_id)
                .style(ButtonStyle::Secondary)
                .label(sample(YES_PHRASES)),
            CreateButton::new(cancel_id)
                .style(ButtonStyle::Secondary)
                .label(sample(NO_PHRASES)),
        ]
        .into(),
    ))]
}
