//! The character model for Discord character chats.

//! This module contains the `Character` struct which represents an AI character
//! that users can chat with.

use bon::Builder;
use core::fmt::{Display, Formatter, Result as FmtResult};
use jiff::Zoned;
use poise::serenity_prelude::all::{Color, UserId};
use serde::{Deserialize, Serialize};
use alloc::collections::{BTreeMap, BTreeSet};

use crate::llm::CharacterModelSettings;

mod lifecycle;
mod ranking;
mod stats;

/// A character.
#[derive(Debug, Clone, Serialize, Deserialize, Builder)]
pub struct Character {
    /// The character's unique ID (a ULID), generated on creation. Used as the file name.
    id: String,
    /// The character's name.
    #[builder(into)]
    name: String,
    /// The character's greeting.
    ///
    /// This is the first message in every conversation.
    #[builder(into)]
    greeting: String,
    /// The Discord user ID of the character's original creator.
    #[builder(into)]
    creator: UserId,
    /// The current version of the character.
    ///
    /// This starts at 0 and increments by 1 with each edit.
    #[builder(default)]
    version: u32,
    /// The ID of the next version of the character.
    ///
    /// If Some, the character will no longer be visible.
    next_version: Option<String>,
    /// The ID of the previous version of the character.
    ///
    /// This is used for rollback purposes.
    previous_version: Option<String>,
    /// The character's nickname.
    ///
    /// This is intended to be a short version of the name, to
    /// more easily start conversations with the character.
    nickname: Option<String>,
    /// A short description of the character.
    ///
    /// This is not read by the model, it is only used for display purposes.
    description: Option<String>,
    /// The character's personality.
    ///
    /// This should be a first-person description of the character.
    ///
    /// This is read by the model, as a guide on how to act.
    personality: Option<String>,
    /// The prompt for the character.
    ///
    /// This should be a list of instructions for how the character should
    /// behave.
    prompt: Option<String>,
    /// The system prompt, always placed as the latest message.
    system_prompt: Option<String>,
    /// The scenario for the character.
    ///
    /// This is meant as the scene, setting, or location that the character
    /// starts in.
    scenario: Option<String>,
    /// The character's avatar's URL.
    ///
    /// Note: Do not set this to the link of an uploaded image on Discord,
    /// as those are temporary. Instead, prefer a link to an image on a
    /// permanent host, such as a CDN or a public image host.
    avatar: Option<String>,
    /// The character's emoji. Usually displayed before the character's name.
    ///
    /// Although this is called "emoji", it actually being an emoji is never
    /// enforced.
    emoji: Option<String>,
    /// The Discord user IDs of anyone who has ever edited the character, if any.
    ///
    /// A `BTreeSet` (not a `HashSet`) so the JSON serialization is deterministic and the stored
    /// file stays stable across rewrites (clean diffs, no spurious churn).
    #[builder(default)]
    all_editors: BTreeSet<UserId>,
    /// The Discord user ID of the latest person to edit the character, if any.
    latest_editor: Option<UserId>,
    /// If Some, the Discord user ID of the character's deleter.
    ///
    /// If Some, the character will no longer be visible.
    deleted_by: Option<UserId>,
    /// The hex color of the character.
    color: Option<Color>,
    /// The time the character was created.
    #[builder(default = Zoned::now())]
    created_at: Zoned,
    /// If Some, the time this version was created.
    edited_at: Option<Zoned>,
    /// If Some, the time the character was deleted.
    deleted_at: Option<Zoned>,
    /// The latest time the character had a conversation with a user.
    latest_conversation: Option<Zoned>,
    /// The number of conversations the character has had with a user.
    ///
    /// This means the amount of times this character has been "spawned".
    ///
    /// A `BTreeMap` (not a `HashMap`) so the JSON serialization is deterministic and the stored
    /// file stays stable across rewrites (clean diffs, no spurious churn).
    #[builder(default)]
    conversations_had_with_user: BTreeMap<UserId, u32>,
    /// The number of conversations the character has had.
    ///
    /// This means the amount of times this character has been "spawned".
    #[builder(default)]
    conversations_had: u32,
    /// The number of words generated by the character.
    #[builder(default)]
    words_generated: u32,
    /// The number of tokens generated by the character.
    #[builder(default)]
    tokens_generated: u32,
    /// The example messages for the character.
    ///
    /// Setting example messages are a great way to teach the character how to
    /// act.
    ///
    /// The first element of the tuple is optionally a user's message, and the
    /// second is the character's response to that message.
    #[builder(default)]
    example_messages: Vec<(Option<String>, String)>,
    /// The model settings override for the character.
    ///
    /// If set, its present fields override the global model settings for this character's requests.
    model_settings: Option<CharacterModelSettings>,
    /// The `ElevenLabs` voice ID linked to the character.
    ///
    /// When set, the text-to-speech button speaks this character's replies in this
    /// voice; otherwise it falls back to the configured generic default voice.
    voice: Option<String>,
    /// The similarity of the character to the input.
    ///
    /// This is `Some` when the user searches a character by name, e.g. `chat` or `delete`. and `None` in e.g. `view`.
    ///
    /// Transient view state, never persisted: rebuilt by `rank_by_similarity` at query time.
    #[serde(skip)]
    similarity: Option<f64>,
}

/// A lightweight projection of a character for the hand-off select menu.
///
/// The menu only needs the label shown to the user and the ID to switch to, so
/// this avoids cloning (and carrying around) whole [`Character`] records just to
/// render 25 select options.
#[derive(Debug, Clone)]
#[expect(
    clippy::module_name_repetitions,
    reason = "this is a projection of a Character, so the shared prefix is meaningful"
)]
pub struct CharacterOption {
    /// The display label (emoji + name), as produced by the character's `Display`.
    label: String,
    /// The character's ID, used as the select option's value.
    id: String,
    /// A short blurb shown under the label in the hand-off menu.
    description: String,
}

impl CharacterOption {
    /// Returns the option's display label.
    #[must_use]
    pub fn label(&self) -> &str {
        &self.label
    }

    /// Returns the option's character ID.
    #[must_use]
    pub fn id(&self) -> &str {
        &self.id
    }

    /// Returns the option's menu description.
    #[must_use]
    pub fn description(&self) -> &str {
        &self.description
    }
}

impl Character {
    /// Returns the character's name.
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Returns the character's greeting message.
    #[must_use]
    pub fn greeting(&self) -> &str {
        &self.greeting
    }

    /// Returns the character's personality description.
    #[must_use]
    pub fn personality(&self) -> Option<&str> {
        self.personality.as_deref()
    }

    /// Returns the character's prompt instructions.
    #[must_use]
    pub fn prompt(&self) -> Option<&str> {
        self.prompt.as_deref()
    }

    /// Returns the character's system prompt.
    #[must_use]
    pub fn system_prompt(&self) -> Option<&str> {
        self.system_prompt.as_deref()
    }

    /// Returns the character's scenario.
    #[must_use]
    pub fn scenario(&self) -> Option<&str> {
        self.scenario.as_deref()
    }

    /// Returns the character's example messages.
    #[must_use]
    pub const fn example_messages(&self) -> &[(Option<String>, String)] {
        self.example_messages.as_slice()
    }

    /// Returns the character's avatar URL.
    #[must_use]
    pub fn avatar(&self) -> Option<&str> {
        self.avatar.as_deref()
    }

    /// Returns the character's embed color.
    #[must_use]
    pub const fn color(&self) -> Option<Color> {
        self.color
    }

    /// Sets the character's embed color.
    pub const fn set_color(&mut self, color: Color) {
        self.color = Some(color);
    }

    /// Returns the character's emoji.
    #[must_use]
    pub fn emoji(&self) -> Option<&str> {
        self.emoji.as_deref()
    }

    /// Returns the character's nickname.
    #[must_use]
    pub fn nickname(&self) -> Option<&str> {
        self.nickname.as_deref()
    }

    /// Returns the character's short description.
    #[must_use]
    pub fn description(&self) -> Option<&str> {
        self.description.as_deref()
    }

    /// Returns the character's version number (zero-based).
    #[must_use]
    pub const fn version(&self) -> u32 {
        self.version
    }

    /// Returns the Discord user ID of the character's original creator.
    #[must_use]
    pub const fn creator(&self) -> UserId {
        self.creator
    }

    /// Returns the Discord user ID of the latest editor, if any.
    #[must_use]
    pub const fn latest_editor(&self) -> Option<UserId> {
        self.latest_editor
    }

    /// Returns the Discord user IDs of everyone who has ever edited the character.
    ///
    /// Sorted by user ID (it is a `BTreeSet`), so the rendered list is stable.
    #[must_use]
    pub const fn all_editors(&self) -> &BTreeSet<UserId> {
        &self.all_editors
    }

    /// Returns the Discord user ID of the character's deleter, if it is deleted.
    #[must_use]
    pub const fn deleted_by(&self) -> Option<UserId> {
        self.deleted_by
    }

    /// Returns the time the character was deleted, if it is deleted.
    #[must_use]
    pub const fn deleted_at(&self) -> Option<&Zoned> {
        self.deleted_at.as_ref()
    }

    /// Returns the time the character was created.
    #[must_use]
    pub const fn created_at(&self) -> &Zoned {
        &self.created_at
    }

    /// Returns the time this version was created, if it is an edit.
    #[must_use]
    pub const fn edited_at(&self) -> Option<&Zoned> {
        self.edited_at.as_ref()
    }

    /// Returns the character's unique ID.
    #[must_use]
    pub fn id(&self) -> &str {
        &self.id
    }

    /// Returns a lightweight hand-off menu option (label + ID + blurb) for this
    /// character. The blurb prefers the short description, then falls back through
    /// the personality, prompt, system prompt, scenario, and finally the greeting,
    /// trimmed to Discord's 100-character select-option limit.
    #[must_use]
    pub fn to_menu_option(&self) -> CharacterOption {
        let blurb = self
            .description()
            .or_else(|| self.personality())
            .or_else(|| self.prompt())
            .or_else(|| self.system_prompt())
            .or_else(|| self.scenario())
            .unwrap_or_else(|| self.greeting());
        CharacterOption {
            label: self.to_string(),
            id: self.id.clone(),
            description: blurb.chars().take(100).collect(),
        }
    }

    /// Returns whether the character is visible (not deleted and not superseded by a newer version).
    #[must_use]
    pub const fn is_visible(&self) -> bool {
        self.deleted_at.is_none() && self.next_version.is_none()
    }

    /// Returns whether the character has been soft-deleted.
    #[must_use]
    pub const fn is_deleted(&self) -> bool {
        self.deleted_at.is_some()
    }

    /// Returns the ID of the next version of this character, if it has been superseded.
    #[must_use]
    pub fn next_version(&self) -> Option<&str> {
        self.next_version.as_deref()
    }

    /// Returns the ID of the previous version of this character, if it has one.
    #[must_use]
    pub fn previous_version(&self) -> Option<&str> {
        self.previous_version.as_deref()
    }

    /// Returns the total number of conversations the character has had.
    #[must_use]
    pub const fn conversations_had(&self) -> u32 {
        self.conversations_had
    }

    /// Returns how many conversations each user has had with this character.
    #[must_use]
    pub const fn conversations_per_user(&self) -> &BTreeMap<UserId, u32> {
        &self.conversations_had_with_user
    }

    /// Returns the number of words this character has generated.
    #[must_use]
    pub const fn words_generated(&self) -> u32 {
        self.words_generated
    }

    /// Returns the number of tokens this character has generated.
    #[must_use]
    pub const fn tokens_generated(&self) -> u32 {
        self.tokens_generated
    }

    /// Returns the character's model settings override, if any.
    #[must_use]
    pub const fn model_settings(&self) -> Option<&CharacterModelSettings> {
        self.model_settings.as_ref()
    }

    /// Returns whether the character has its own model settings override.
    #[must_use]
    pub const fn has_model_settings(&self) -> bool {
        self.model_settings.is_some()
    }

    /// Sets the character's model settings override.
    pub fn set_model_settings(&mut self, model_settings: CharacterModelSettings) {
        self.model_settings = Some(model_settings);
    }

    /// Returns the character's linked `ElevenLabs` voice ID, if any.
    #[must_use]
    pub fn voice(&self) -> Option<&str> {
        self.voice.as_deref()
    }

    /// Sets (or, with `None`, clears) the character's linked `ElevenLabs` voice ID.
    pub fn set_voice(&mut self, voice: Option<String>) {
        self.voice = voice;
    }

    /// Marks the character as deleted by the given user, recording the time of deletion.
    pub fn mark_deleted(&mut self, deleted_by: UserId) {
        self.deleted_by = Some(deleted_by);
        self.deleted_at = Some(Zoned::now());
    }

    /// Clears the character's deleted state, making it visible again.
    pub fn restore(&mut self) {
        self.deleted_by = None;
        self.deleted_at = None;
    }

    /// Sets the ID of the next version of this character, hiding it from view.
    pub fn set_next_version(&mut self, next_version: String) {
        self.next_version = Some(next_version);
    }

    /// Returns the similarity indicator for display.
    ///
    /// Returns e.g. ` | 75% namnlikhet` if `Some(0.75)`, otherwise returns an empty String.
    #[must_use]
    pub fn similarity(&self) -> String {
        self.similarity.map_or_else(String::new, |similarity| {
            format!(" | {:.0}% namnlikhet", similarity * 100.0_f64)
        })
    }

}

impl Display for Character {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        if let Some(emoji) = &self.emoji {
            write!(f, "{emoji} ")?;
        }
        write!(f, "{}", self.name())
    }
}

/// Shared character fixtures for the model's test modules (this module plus the
/// `ranking` child), so the minimal-character builder lives in one place.
#[cfg(test)]
mod test_support {
    use super::Character;
    use serenity::all::UserId;

    /// Builds a minimal visible character with the given ID and name.
    pub(super) fn basic_character(id: &str, name: &str) -> Character {
        Character::builder()
            .id(id.to_owned())
            .name(name)
            .greeting("hello")
            .creator(UserId::new(1))
            .build()
    }
}

/// Tests for character similarity ranking.
#[cfg(test)]
mod tests {
    use super::Character;
    use super::test_support::basic_character;
    use crate::{
        llm::CharacterModelSettings,
        models::modals::{EditCharacterModal, SecondEditCharacterModal},
    };
    use alloc::collections::{BTreeMap, BTreeSet};
    use jiff::Zoned;
    use serenity::all::{Color, UserId};

    /// Builds a pair of edit modals that leave every field untouched.
    fn empty_edit_modals() -> (EditCharacterModal, SecondEditCharacterModal) {
        (
            EditCharacterModal {
                name: None,
                greeting: None,
                nickname: None,
                description: None,
                personality: None,
            },
            SecondEditCharacterModal {
                avatar: None,
                emoji: None,
                system_prompt: None,
                prompt: None,
                scenario: None,
            },
        )
    }

    /// Builds a character with every editable content field populated.
    fn populated_character() -> Character {
        Character::builder()
            .id("id".to_owned())
            .name("Harry")
            .greeting("hej")
            .creator(UserId::new(1))
            .nickname("H".to_owned())
            .description("kort".to_owned())
            .personality("snäll".to_owned())
            .avatar("https://example.com/a.png".to_owned())
            .emoji("🤩".to_owned())
            .system_prompt("system".to_owned())
            .prompt("prompt".to_owned())
            .scenario("scen".to_owned())
            .build()
    }

    /// The edit modals are pre-filled with every current field value, so the forms
    /// open populated with the existing character instead of blank.
    #[test]
    fn edit_modal_defaults_prefill_every_field() {
        let (first, second) = populated_character().edit_modal_defaults();
        assert_eq!(first.name.as_deref(), Some("Harry"), "the name is pre-filled");
        assert_eq!(
            first.greeting.as_deref(),
            Some("hej"),
            "the greeting is pre-filled"
        );
        assert_eq!(
            first.nickname.as_deref(),
            Some("H"),
            "the nickname is pre-filled"
        );
        assert_eq!(
            first.description.as_deref(),
            Some("kort"),
            "the description is pre-filled"
        );
        assert_eq!(
            first.personality.as_deref(),
            Some("snäll"),
            "the personality is pre-filled"
        );
        assert_eq!(
            second.avatar.as_deref(),
            Some("https://example.com/a.png"),
            "the avatar is pre-filled"
        );
        assert_eq!(
            second.emoji.as_deref(),
            Some("🤩"),
            "the emoji is pre-filled"
        );
        assert_eq!(
            second.system_prompt.as_deref(),
            Some("system"),
            "the system prompt is pre-filled"
        );
        assert_eq!(
            second.prompt.as_deref(),
            Some("prompt"),
            "the prompt is pre-filled"
        );
        assert_eq!(
            second.scenario.as_deref(),
            Some("scen"),
            "the scenario is pre-filled"
        );
    }

    /// Required fields are always pre-filled, while an absent optional field stays empty
    /// so the user is not shown a value that does not exist.
    #[test]
    fn edit_modal_defaults_leave_absent_optionals_empty() {
        let (first, second) = basic_character("id", "Harry").edit_modal_defaults();
        assert_eq!(
            first.name.as_deref(),
            Some("Harry"),
            "the required name is always pre-filled"
        );
        assert_eq!(
            first.greeting.as_deref(),
            Some("hello"),
            "the required greeting is always pre-filled"
        );
        assert_eq!(
            first.nickname, None,
            "an absent optional field stays empty"
        );
        assert_eq!(
            second.prompt, None,
            "an absent optional field stays empty"
        );
    }

    /// Submitting the pre-filled modals unchanged leaves every content field identical.
    #[test]
    fn editing_with_prefilled_defaults_round_trips() {
        let mut character = populated_character();
        let (first, second) = character.edit_modal_defaults();
        character.edit_from_modals(UserId::new(2), first, second);
        assert_eq!(character.name(), "Harry", "the name round-trips unchanged");
        assert_eq!(
            character.greeting(),
            "hej",
            "the greeting round-trips unchanged"
        );
        assert_eq!(
            character.nickname(),
            Some("H"),
            "the nickname round-trips unchanged"
        );
        assert_eq!(
            character.description(),
            Some("kort"),
            "the description round-trips unchanged"
        );
        assert_eq!(
            character.personality(),
            Some("snäll"),
            "the personality round-trips unchanged"
        );
        assert_eq!(
            character.avatar(),
            Some("https://example.com/a.png"),
            "the avatar round-trips unchanged"
        );
        assert_eq!(
            character.emoji(),
            Some("🤩"),
            "the emoji round-trips unchanged"
        );
        assert_eq!(
            character.system_prompt(),
            Some("system"),
            "the system prompt round-trips unchanged"
        );
        assert_eq!(
            character.prompt(),
            Some("prompt"),
            "the prompt round-trips unchanged"
        );
        assert_eq!(
            character.scenario(),
            Some("scen"),
            "the scenario round-trips unchanged"
        );
    }

    /// Rolling back to an older version reverts the content fields to that version
    /// but keeps the current version's accumulated stats and links the new version
    /// back to the one it superseded.
    #[test]
    fn rollback_to_reverts_content_and_keeps_stats() {
        let old = Character::builder()
            .id("v0".to_owned())
            .name("Old Name")
            .greeting("old greeting")
            .creator(UserId::new(1))
            .personality("old personality".to_owned())
            .build();
        let mut current = Character::builder()
            .id("v1".to_owned())
            .name("New Name")
            .greeting("new greeting")
            .creator(UserId::new(1))
            .version(1_u32)
            .personality("new personality".to_owned())
            .conversations_had(7_u32)
            .build();

        current.rollback_to(UserId::new(3), &old);

        assert_eq!(
            current.name(),
            "Old Name",
            "the content reverts to the old version's name"
        );
        assert_eq!(
            current.greeting(),
            "old greeting",
            "the content reverts to the old version's greeting"
        );
        assert_eq!(
            current.personality(),
            Some("old personality"),
            "the content reverts to the old version's personality"
        );
        assert_eq!(
            current.conversations_had(),
            7,
            "the accumulated stats from the current version are kept"
        );
        assert_eq!(
            current.version,
            2,
            "the rolled-back version's number is bumped past the current one"
        );
        assert_eq!(
            current.previous_version(),
            Some("v1"),
            "the new version links back to the version it superseded"
        );
        assert_ne!(
            current.id(),
            "v1",
            "a rollback creates a new version with a fresh id"
        );
        assert!(
            current.is_visible(),
            "the rolled-back version is visible"
        );
    }

    /// Every distinct editor is accumulated, not just the latest one.
    #[test]
    fn all_editors_accumulates_every_editor() {
        let mut character = basic_character("id", "Harry");
        assert!(
            character.all_editors().is_empty(),
            "a fresh character has no editors"
        );

        let (first, second) = empty_edit_modals();
        character.edit_from_modals(UserId::new(2), first, second);
        let (later_first, later_second) = empty_edit_modals();
        character.edit_from_modals(UserId::new(3), later_first, later_second);

        assert!(
            character.all_editors().contains(&UserId::new(2)),
            "the first editor is recorded"
        );
        assert!(
            character.all_editors().contains(&UserId::new(3)),
            "the second editor is recorded"
        );
        assert_eq!(
            character.all_editors().len(),
            2,
            "every distinct editor is kept, not just the latest"
        );
        assert_eq!(
            character.latest_editor(),
            Some(UserId::new(3)),
            "the latest editor is the most recent one"
        );
    }

    /// Deletion records the deleter and time and hides the character; a restore
    /// clears both and makes it visible again.
    #[test]
    fn deletion_metadata_records_the_deleter_and_clears_on_restore() {
        let mut character = basic_character("id", "Harry");
        assert!(
            character.deleted_by().is_none(),
            "a fresh character has no deleter"
        );
        assert!(
            character.deleted_at().is_none(),
            "a fresh character has no deletion time"
        );

        character.mark_deleted(UserId::new(2));
        assert_eq!(
            character.deleted_by(),
            Some(UserId::new(2)),
            "the deleter is recorded"
        );
        assert!(
            character.deleted_at().is_some(),
            "the deletion time is recorded"
        );
        assert!(character.is_deleted(), "a marked character reads as deleted");
        assert!(
            !character.is_visible(),
            "a deleted character is not visible"
        );

        character.restore();
        assert!(
            character.deleted_by().is_none(),
            "restoring clears the deleter"
        );
        assert!(
            character.deleted_at().is_none(),
            "restoring clears the deletion time"
        );
        assert!(
            !character.is_deleted(),
            "a restored character no longer reads as deleted"
        );
        assert!(
            character.is_visible(),
            "a restored character is visible again"
        );
    }

    /// Setting a voice is readable back, and a rollback carries the older
    /// version's linked voice forward like the rest of its content.
    #[test]
    fn voice_is_set_and_carried_across_rollback() {
        let mut character = basic_character("id", "Harry");
        assert!(
            character.voice().is_none(),
            "a fresh character has no linked voice"
        );
        character.set_voice(Some("voice-abc".to_owned()));
        assert_eq!(
            character.voice(),
            Some("voice-abc"),
            "the linked voice is readable back"
        );

        let mut old = basic_character("v0", "Harry");
        old.set_voice(Some("old-voice".to_owned()));
        let mut head = Character::builder()
            .id("v1".to_owned())
            .name("Harry")
            .greeting("hello")
            .creator(UserId::new(1))
            .version(1_u32)
            .build();
        head.rollback_to(UserId::new(3), &old);
        assert_eq!(
            head.voice(),
            Some("old-voice"),
            "a rollback restores the older version's linked voice"
        );
    }

    /// Builds a character with every field populated, including accumulated stats,
    /// version lineage, editors, and the model/voice overrides.
    fn fully_used_character() -> Character {
        Character::builder()
            .id("orig".to_owned())
            .name("Harry")
            .greeting("hej")
            .creator(UserId::new(1))
            .version(2_u32)
            .previous_version("orig-v1".to_owned())
            .nickname("H".to_owned())
            .description("kort".to_owned())
            .personality("snäll".to_owned())
            .prompt("prompt".to_owned())
            .system_prompt("system".to_owned())
            .scenario("scen".to_owned())
            .avatar("https://example.com/a.png".to_owned())
            .emoji("🤩".to_owned())
            .color(Color::new(0x0000_FF00))
            .all_editors(BTreeSet::from([UserId::new(9)]))
            .latest_editor(UserId::new(9))
            .latest_conversation(Zoned::now())
            .conversations_had_with_user(BTreeMap::from([(UserId::new(9), 4_u32)]))
            .conversations_had(5_u32)
            .words_generated(100_u32)
            .tokens_generated(200_u32)
            .example_messages(vec![(Some("hi".to_owned()), "there".to_owned())])
            .model_settings(CharacterModelSettings {
                model: Some("gpt".to_owned()),
                temperature: Some(0.7),
            })
            .voice("voice-abc".to_owned())
            .build()
    }

    /// Cloning mints a fresh identity for a new owner and resets the version
    /// lineage and every accumulated stat.
    #[test]
    fn duplicate_resets_identity_lineage_and_stats() {
        let original = fully_used_character();
        let clone = original.duplicate(UserId::new(2), Some("Harald".to_owned()));

        assert_ne!(clone.id(), "orig", "a clone gets a fresh id");
        assert_eq!(clone.name(), "Harald", "the clone takes the given name");
        assert_eq!(
            clone.creator(),
            UserId::new(2),
            "the cloning user becomes the new creator"
        );

        assert_eq!(clone.version(), 0, "the clone starts at version 0");
        assert_eq!(
            clone.previous_version(),
            None,
            "the clone has no previous version"
        );
        assert_eq!(clone.next_version(), None, "the clone has no next version");
        assert!(clone.is_visible(), "the clone is visible");
        assert!(!clone.is_deleted(), "the clone is not deleted");

        assert!(
            clone.all_editors().is_empty(),
            "the clone carries over no editors"
        );
        assert_eq!(clone.latest_editor(), None, "the clone has no latest editor");
        assert!(clone.edited_at().is_none(), "the clone has no edit time");
        assert_eq!(
            clone.conversations_had(),
            0,
            "the clone's conversation count is reset"
        );
        assert!(
            clone.conversations_per_user().is_empty(),
            "the clone's per-user counts are reset"
        );
        assert_eq!(
            clone.words_generated(),
            0,
            "the clone's word count is reset"
        );
        assert_eq!(
            clone.tokens_generated(),
            0,
            "the clone's token count is reset"
        );
    }

    /// Cloning copies every content field, including the model and voice overrides.
    #[test]
    fn duplicate_copies_content_and_overrides() {
        let original = fully_used_character();
        let clone = original.duplicate(UserId::new(2), Some("Harald".to_owned()));

        assert_eq!(clone.greeting(), "hej", "the greeting is copied");
        assert_eq!(clone.nickname(), Some("H"), "the nickname is copied");
        assert_eq!(clone.description(), Some("kort"), "the description is copied");
        assert_eq!(
            clone.personality(),
            Some("snäll"),
            "the personality is copied"
        );
        assert_eq!(clone.prompt(), Some("prompt"), "the prompt is copied");
        assert_eq!(
            clone.system_prompt(),
            Some("system"),
            "the system prompt is copied"
        );
        assert_eq!(clone.scenario(), Some("scen"), "the scenario is copied");
        assert_eq!(
            clone.avatar(),
            Some("https://example.com/a.png"),
            "the avatar is copied"
        );
        assert_eq!(clone.emoji(), Some("🤩"), "the emoji is copied");
        assert_eq!(
            clone.color(),
            Some(Color::new(0x0000_FF00)),
            "the color is copied"
        );
        let expected_examples = vec![(Some("hi".to_owned()), "there".to_owned())];
        assert_eq!(
            clone.example_messages(),
            expected_examples.as_slice(),
            "the example messages are copied"
        );
        assert_eq!(
            clone.model_settings().and_then(|settings| settings.model.as_deref()),
            Some("gpt"),
            "the model override is copied"
        );
        assert!(
            clone
                .model_settings()
                .and_then(|settings| settings.temperature)
                .is_some(),
            "the temperature override is copied"
        );
        assert_eq!(clone.voice(), Some("voice-abc"), "the voice is copied");
    }

    /// An omitted name defaults to the original's name suffixed with " (kopia)".
    #[test]
    fn duplicate_defaults_name_to_kopia_suffix() {
        let original = basic_character("orig", "Harry");
        let clone = original.duplicate(UserId::new(2), None);
        assert_eq!(
            clone.name(),
            "Harry (kopia)",
            "an omitted name defaults to the original suffixed with (kopia)"
        );
    }

    /// An explicit name is used verbatim instead of the default suffix.
    #[test]
    fn duplicate_uses_the_provided_name() {
        let original = basic_character("orig", "Harry");
        let clone = original.duplicate(UserId::new(2), Some("Harald".to_owned()));
        assert_eq!(clone.name(), "Harald", "an explicit name is used as-is");
    }
}
