//! The message model: a single turn in a conversation.
//!
//! Messages are embedded inline in the history records that own them (see
//! [`crate::models::history`]); a message's ID is the Discord message ID when it came from a user,
//! otherwise a generated ULID.

use bon::Builder;
use core::time::Duration;
use nonempty::NonEmpty;
use serde::{Deserialize, Serialize};
use serenity::all::{Message as DiscordMessage, MessageId, UserId};
use tracing::warn;
use ulid::Ulid;

mod attachments;

pub use attachments::{
    AttachmentMode, DescribedAttachment, EncodedAudio, MediaMode, audio_format_from_url,
};

/// A chat message between a user and a character.
///
/// Messages can be created from Discord messages, generated by AI, or be
/// system messages. They support revision history for edits.
#[derive(Debug, Clone, Serialize, Deserialize, Builder)]
pub struct Message {
    /// If this message originates from Discord, the message's Discord ID, otherwise a ulid ID.
    #[builder(default = Ulid::new().to_string(), with = |id: MessageId| id.to_string())]
    id: String,
    /// The "parts" of the message. A message will ONLY have multiple parts if created from a user's Discord
    /// message. If so, the "parts" of it are every line.
    ///
    /// This allows the user to "send" multiple messages in one, like:
    ///
    /// ```text
    /// hello
    /// system: message
    /// ai: what
    /// steve: no
    /// ```
    #[builder(into)]
    parts: Parts,
    /// If Some, the time it took to generate this message.
    elapsed: Option<Duration>,
    /// Previous revisions of this message, created when edited.
    #[builder(default)]
    revisions: Vec<Revision>,
    /// The URLs of all attached images, if any.
    #[builder(default)]
    #[serde(rename = "images")]
    attachments: Vec<String>,
    /// Cached vision-model descriptions of `attachments`, keyed by URL. Filled lazily the first
    /// time a model without vision needs them, and empty otherwise.
    #[builder(default)]
    #[serde(default)]
    described: Vec<DescribedAttachment>,
    /// Base64-encoded voice attachments, keyed by URL. Filled transiently when the active model
    /// accepts audio so the clip can be sent natively; never persisted.
    #[builder(default)]
    #[serde(skip)]
    encoded_audio: Vec<EncodedAudio>,
    /// The message "revision," 0 is the original (unedited) message, 1 is the
    /// first edit, 2 is the second edit, etc.
    #[builder(default)]
    revision: usize,
    /// Whether this message is a failed-generation notice (a timeout, an empty
    /// completion, or a request error) rather than a genuine reply, so it renders
    /// as a distinct error instead of as the character speaking.
    #[builder(default)]
    #[serde(default)]
    error: bool,
}

/// A non-empty list of message parts.
///
/// A message consists of multiple parts when it is created from a user's
/// Discord message, where each line becomes a separate part.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Parts(NonEmpty<Part>);

/// A part of a message, containing the content and the role.
#[derive(Debug, Default, Clone, Serialize, Deserialize, Builder)]
pub struct Part {
    /// The content of this part.
    content: String,
    /// The role of this part (User, Assistant, or System).
    role: Role,
}

/// A revision of a message, created when the message is edited.
#[derive(Debug, Clone, Serialize, Deserialize, Builder)]
pub struct Revision {
    /// The parts of this revision.
    #[builder(into)]
    parts: Parts,
    /// The Discord user ID of the editor, if any.
    #[builder(into)]
    editor: Option<UserId>,
}

/// The role of a message part, indicating who sent the message.
#[derive(Debug, Default, Clone, Copy, Serialize, Deserialize)]
pub enum Role {
    /// The message was sent by a user.
    #[default]
    User,
    /// The message was generated by the AI.
    Assistant,
    /// A system message.
    System,
}

impl Message {
    /// Returns the ID of this message.
    #[must_use]
    pub fn id(&self) -> &str {
        &self.id
    }

    /// Creates a new assistant message.
    ///
    /// Unsplit on newlines.
    pub fn new_assistant<C: Into<String>>(content: C) -> Self {
        Self::builder()
            .parts((content.into(), Role::Assistant))
            .build()
    }

    /// Creates a new user message.
    ///
    /// Unsplit on newlines.
    pub fn new_user<C: Into<String>>(content: C) -> Self {
        Self::builder().parts((content.into(), Role::User)).build()
    }

    /// Creates a new system message.
    ///
    /// Unsplit on newlines.
    pub fn new_system<C: Into<String>>(content: C) -> Self {
        Self::builder()
            .parts((content.into(), Role::System))
            .build()
    }

    /// Edits the message content, creating a new revision.
    ///
    /// The new content is appended as a fresh revision and the cursor moves to it; revision 0
    /// (the original content) is left untouched, so an undo can return to it.
    pub fn edit<C, E>(&mut self, content: C, editor: E)
    where
        C: Into<String>,
        E: Into<UserId>,
    {
        self.revisions.push(
            Revision::builder()
                .parts((content.into(), Role::Assistant))
                .editor(editor)
                .build(),
        );
        self.revision = self.revisions.len();
    }

    /// Returns the parts of the message at the current version.
    ///
    /// Version 0 is the original message, version 1 is the first revision, etc.
    #[must_use]
    pub fn chosen_revision(&self) -> &Parts {
        match self.revision {
            0 => &self.parts,
            other => self
                .revisions
                .get(other.saturating_sub(1))
                .map_or(&self.parts, |revision| &revision.parts),
        }
    }

    /// Returns the number of revisions (edits) this message has.
    #[must_use]
    pub const fn revisions_count(&self) -> usize {
        self.revisions.len()
    }

    #[must_use]
    /// The editor of the currently chosen revision, if any.
    pub fn current_editor(&self) -> Option<UserId> {
        match self.revision {
            0 => None,
            _ => self.revisions.get(self.revision.saturating_sub(1))?.editor,
        }
    }

    /// Returns the current version of this message.
    ///
    /// Version 0 is the original message, version 1 is the first revision, etc.
    #[must_use]
    pub const fn revision(&self) -> usize {
        self.revision
    }

    /// Whether this message is a failed-generation notice rather than a genuine reply.
    #[must_use]
    pub const fn is_error(&self) -> bool {
        self.error
    }

    /// Marks this message as a failed-generation notice (or clears the mark).
    pub const fn set_error(&mut self, error: bool) {
        self.error = error;
    }

    /// Undoes an edit by cycling to the previous revision.
    ///
    /// If already at the original message, cycles to the last revision.
    pub const fn undo(&mut self) {
        self.revision = self
            .revision
            .saturating_add(self.revisions_count())
            .strict_rem(self.revisions_count().saturating_add(1));
    }

    /// Redoes an edit by cycling to the next revision.
    ///
    /// If already at the last revision, cycles to the original message.
    pub const fn redo(&mut self) {
        self.revision = self
            .revision
            .saturating_add(1)
            .strict_rem(self.revisions_count().saturating_add(1));
    }

    /// Returns the time it took for this message to generate, if it originates from an LLM.
    #[must_use]
    pub const fn time_taken(&self) -> Option<Duration> {
        self.elapsed
    }
}

impl Parts {
    /// Returns the first (head) part of the message.
    #[must_use]
    pub const fn head(&self) -> &Part {
        &self.0.head
    }
}

impl Part {
    /// Returns the content of this part.
    #[must_use]
    pub fn content(&self) -> &str {
        &self.content
    }
}

impl From<(String, Duration)> for Message {
    fn from((response, time_taken): (String, Duration)) -> Self {
        Self::builder()
            .parts((response, Role::Assistant))
            .elapsed(time_taken)
            .build()
    }
}

/// Splits `text` into one [`Part`] per line, taking each line's role from its
/// `name: ` prefix (`ai` maps to assistant, `system` to system, anything else to
/// the user), or attributing the whole line to `author` when it has no prefix.
/// Every line is [`Role::Assistant`] when `from_bot` is set.
fn parts_from_lines(text: &str, author: &str, from_bot: bool) -> Vec<Part> {
    text.lines()
        .map(|line| {
            let (name, content) = if let Some((name, _)) = line.split_once(": ") {
                (name, line.to_owned())
            } else {
                (author, format!("{author}: {line}"))
            };
            let role = if from_bot || name.eq_ignore_ascii_case("ai") {
                Role::Assistant
            } else if name.eq_ignore_ascii_case("system") {
                Role::System
            } else {
                Role::User
            };
            Part::builder().content(content).role(role).build()
        })
        .collect()
}

impl From<(&DiscordMessage, String)> for Message {
    fn from((message, author): (&DiscordMessage, String)) -> Self {
        Self::builder()
            .id(message.id)
            .parts(parts_from_lines(
                &message.content,
                &author,
                message.author.bot(),
            ))
            .attachments(
                message
                    .attachments
                    .iter()
                    .map(|attachment| attachment.url.to_string())
                    .collect::<Vec<String>>(),
            )
            .build()
    }
}

impl From<Vec<Part>> for Parts {
    fn from(parts: Vec<Part>) -> Self {
        let Some(nonempty) = NonEmpty::from_vec(parts) else {
            warn!("constructed Parts from an empty list of parts, substituting a blank part");
            return Self(NonEmpty::default());
        };
        Self(nonempty)
    }
}

impl From<(String, Role)> for Parts {
    fn from((content, role): (String, Role)) -> Self {
        Self(NonEmpty::new(
            Part::builder().content(content).role(role).build(),
        ))
    }
}

/// Tests for message revision navigation and conversion.
#[cfg(test)]
mod tests {
    use super::{Message, Part, Parts, Role, parts_from_lines};

    /// Builds a system message edited twice, leaving two revisions on top of the original.
    fn message_with_two_edits() -> Message {
        let mut message = Message::new_system("original");
        message.edit("first", 1_u64);
        message.edit("second", 1_u64);
        message
    }

    /// Editing records each revision and leaves the cursor on the newest one.
    #[test]
    fn edits_advance_to_the_newest_revision() {
        let message = message_with_two_edits();
        assert_eq!(
            message.revisions_count(),
            2,
            "two edits create two revisions"
        );
        assert_eq!(
            message.revision(),
            2,
            "editing moves the cursor to the newest revision"
        );
        assert_eq!(
            message.chosen_revision().head().content(),
            "second",
            "the newest revision holds the latest content"
        );
    }

    /// `undo` cycles backward through revisions and wraps to the newest at the original.
    #[test]
    fn undo_cycles_backward_and_wraps() {
        let mut message = message_with_two_edits();
        message.undo();
        assert_eq!(message.revision(), 1, "undo steps back one revision");
        assert_eq!(
            message.chosen_revision().head().content(),
            "first",
            "revision one holds the first edit"
        );
        message.undo();
        assert_eq!(message.revision(), 0, "undo reaches the original message");
        assert_eq!(
            message.chosen_revision().head().content(),
            "original",
            "revision zero holds the original content"
        );
        message.undo();
        assert_eq!(
            message.revision(),
            2,
            "undo from the original wraps to the newest revision"
        );
    }

    /// `redo` cycles forward through revisions and wraps to the original at the newest.
    #[test]
    fn redo_cycles_forward_and_wraps() {
        let mut message = message_with_two_edits();
        message.redo();
        assert_eq!(
            message.revision(),
            0,
            "redo from the newest revision wraps to the original"
        );
        message.redo();
        assert_eq!(message.revision(), 1, "redo steps forward one revision");
        message.redo();
        assert_eq!(message.revision(), 2, "redo reaches the newest revision");
    }

    /// Undo and redo on an unedited message (zero revisions) stay on the original
    /// rather than panicking on the modulo, since most replies are never edited.
    #[test]
    fn undo_and_redo_are_no_ops_without_revisions() {
        let mut message = Message::new_system("only");
        assert_eq!(message.revisions_count(), 0, "a fresh message has no edits");
        message.undo();
        assert_eq!(message.revision(), 0, "undo stays on the original revision");
        message.redo();
        assert_eq!(message.revision(), 0, "redo stays on the original revision");
        assert_eq!(
            message.chosen_revision().head().content(),
            "only",
            "the original content is unchanged"
        );
    }

    /// A single-part conversion keeps the content, while an empty list falls back to a blank part.
    #[test]
    fn parts_conversions_preserve_content_or_blank() {
        let single: Parts = ("hi".to_owned(), Role::User).into();
        assert_eq!(
            single.head().content(),
            "hi",
            "a single-part conversion keeps the content"
        );

        let empty: Parts = Vec::<Part>::new().into();
        assert!(
            empty.head().content().is_empty(),
            "an empty part list falls back to a blank part"
        );
    }

    /// A prefixed line keeps its whole text as content and reads its role from the prefix.
    #[test]
    fn prefixed_lines_take_their_role_from_the_name() {
        let parts = parts_from_lines("system: be terse\nai: sure\nAlice: hi", "Bob", false);
        assert_eq!(parts.len(), 3, "one part per line");

        let first = parts.first();
        assert_eq!(
            first.map(|part| part.content.as_str()),
            Some("system: be terse"),
            "the whole prefixed line is kept as content"
        );
        assert!(
            matches!(first.map(|part| part.role), Some(Role::System)),
            "a system prefix maps to the system role"
        );
        assert!(
            matches!(parts.get(1).map(|part| part.role), Some(Role::Assistant)),
            "an ai prefix maps to the assistant role"
        );
        assert!(
            matches!(parts.get(2).map(|part| part.role), Some(Role::User)),
            "any other prefix maps to the user role"
        );
    }

    /// An unprefixed line is attributed to the author and prefixed with their name.
    #[test]
    fn unprefixed_lines_are_attributed_to_the_author() {
        let parts = parts_from_lines("hello", "Bob", false);
        assert_eq!(parts.len(), 1, "a single line yields a single part");

        let first = parts.first();
        assert_eq!(
            first.map(|part| part.content.as_str()),
            Some("Bob: hello"),
            "the author name is prefixed onto the content"
        );
        assert!(
            matches!(first.map(|part| part.role), Some(Role::User)),
            "an author line defaults to the user role"
        );
    }

    /// A bot author forces every line to the assistant role regardless of any prefix.
    #[test]
    fn bot_author_forces_the_assistant_role() {
        let parts = parts_from_lines("system: still assistant\nplain line", "Harry", true);
        assert!(
            parts
                .iter()
                .all(|part| matches!(part.role, Role::Assistant)),
            "every line from a bot author is an assistant part"
        );
    }

    /// A mid-line ": " is still parsed as a prefix, splitting name from the kept content.
    #[test]
    fn a_mid_line_colon_is_parsed_as_a_prefix() {
        let parts = parts_from_lines("I said: hi", "Bob", false);
        assert_eq!(parts.len(), 1, "a single line yields a single part");

        let first = parts.first();
        assert_eq!(
            first.map(|part| part.content.as_str()),
            Some("I said: hi"),
            "the whole line is still kept as content"
        );
        assert!(
            matches!(first.map(|part| part.role), Some(Role::User)),
            "an unrecognized prefix defaults to the user role"
        );
    }
}
