//! The message model: a single turn in a conversation.
//!
//! Messages are stored once in their own `native_db` table, keyed by [`Message`]'s `id`, and
//! referenced by ID from history records (see [`crate::models::history`]). A message's ID is the
//! Discord message ID when it came from a user, otherwise a generated ULID.

use bon::Builder;
use core::time::Duration;
use jiff::Zoned;
use native_db::{ToKey as _, native_db};
use native_model::{Model as _, native_model};
use nonempty::NonEmpty;
use rig::{
    OneOrMany,
    agent::Text,
    message::{AssistantContent, Message as RigMessage, UserContent},
};
use serde::{Deserialize, Serialize};
use serenity::all::{Attachment, Message as DiscordMessage, MessageId, UserId};
use tracing::warn;
use ulid::Ulid;

use crate::models::character::Character;

/// Discord voice messages are uploaded as `.ogg` attachments.
const PROBABLE_DISCORD_VOICE_RECORDING: &str = ".ogg";

/// A chat message between a user and a character.
///
/// Messages can be created from Discord messages, generated by AI, or be
/// system messages. They support revision history for edits.
#[derive(Debug, Clone, Serialize, Deserialize, Builder)]
#[native_model(id = 8, version = 1, with = crate::codec::Json)]
#[native_db]
pub struct Message {
    /// If this message originates from Discord, the message's Discord ID, otherwise a ulid ID.
    ///
    /// Used as the primary key; messages are stored once and referenced by history records.
    #[primary_key]
    #[builder(default = Ulid::new().to_string(), with = |id: MessageId| id.to_string())]
    id: String,
    /// The "parts" of the message. A message will ONLY have multiple parts if created from a user's Discord
    /// message. If so, the "parts" of it are every line.
    ///
    /// This allows the user to "send" multiple messages in one, like:
    ///
    /// ```text
    /// hello
    /// system: message
    /// ai: what
    /// steve: no
    /// ```
    #[builder(into)]
    parts: Parts,
    /// The time this message was created.
    #[builder(default = Zoned::now())]
    created: Zoned,
    /// If Some, the time it took to generate this message.
    elapsed: Option<Duration>,
    /// Previous revisions of this message, created when edited.
    #[builder(default)]
    revisions: Vec<Revision>,
    /// The URLs of all attached images, if any.
    #[builder(default, with = |attachments: &[Attachment]| attachments.iter().map(|attachment| attachment.url.to_string()).collect::<Vec<String>>()  )]
    #[serde(rename = "images")]
    attachments: Vec<String>,
    /// The message "revision," 0 is the original (unedited) message, 1 is the
    /// first edit, 2 is the second edit, etc.
    #[builder(default)]
    revision: usize,
}

/// A non-empty list of message parts.
///
/// A message consists of multiple parts when it is created from a user's
/// Discord message, where each line becomes a separate part.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Parts(NonEmpty<Part>);

/// A part of a message, containing the name of the speaker, the content, and the role.
#[derive(Debug, Default, Clone, Serialize, Deserialize, Builder)]
pub struct Part {
    /// The name of the speaker in this part.
    name: String,
    /// The content of this part.
    content: String,
    /// The role of this part (User, Assistant, or System).
    role: Role,
}

/// A revision of a message, created when the message is edited.
#[derive(Debug, Clone, Serialize, Deserialize, Builder)]
pub struct Revision {
    /// The time this revision was created.
    #[builder(default = Zoned::now())]
    created: Zoned,
    /// The parts of this revision.
    #[builder(into)]
    parts: Parts,
    /// The Discord user ID of the editor, if any.
    #[builder(into)]
    editor: Option<UserId>,
}

/// The role of a message part, indicating who sent the message.
#[derive(Debug, Default, Clone, Copy, Serialize, Deserialize)]
pub enum Role {
    /// The message was sent by a user.
    #[default]
    User,
    /// The message was generated by the AI.
    Assistant,
    /// A system message.
    System,
}

impl Message {
    /// Returns the ID of this message.
    #[must_use]
    pub fn id(&self) -> &str {
        &self.id
    }

    /// Creates a new assistant message.
    ///
    /// Unsplit on newlines.
    pub fn new_assistant<C: Into<String>>(content: C, character: &Character) -> Self {
        Self::builder()
            .parts((character.name().to_owned(), content.into(), Role::Assistant))
            .build()
    }

    /// Creates a new user message.
    ///
    /// Unsplit on newlines.
    pub fn new_user<A, C>(author: A, content: C) -> Self
    where
        A: Into<String>,
        C: Into<String>,
    {
        Self::builder()
            .parts((author.into(), content.into(), Role::User))
            .build()
    }

    /// Creates a new system message.
    ///
    /// Unsplit on newlines.
    pub fn new_system<C: Into<String>>(content: C) -> Self {
        Self::builder()
            .parts(("System".to_owned(), content.into(), Role::System))
            .build()
    }

    /// Edits the message content, creating a new revision.
    ///
    /// The new content is appended as a fresh revision and the cursor moves to it; revision 0
    /// (the original content) is left untouched, so an undo can return to it.
    pub fn edit<A, C, E>(&mut self, author: A, content: C, editor: Option<E>)
    where
        A: Into<String>,
        C: Into<String>,
        E: Into<UserId>,
    {
        self.revisions.push(
            Revision::builder()
                .parts((author.into(), content.into(), Role::Assistant))
                .maybe_editor(editor)
                .build(),
        );
        self.revision = self.revisions.len();
    }

    /// Returns the parts of the message at the current version.
    ///
    /// Version 0 is the original message, version 1 is the first revision, etc.
    #[must_use]
    pub fn chosen_revision(&self) -> &Parts {
        match self.revision {
            0 => &self.parts,
            other => self
                .revisions
                .get(other.saturating_sub(1))
                .map_or(&self.parts, |revision| &revision.parts),
        }
    }

    /// Returns the number of revisions (edits) this message has.
    #[must_use]
    pub const fn revisions_count(&self) -> usize {
        self.revisions.len()
    }

    #[must_use]
    /// The editor of the currently chosen revision, if any.
    pub fn current_editor(&self) -> Option<UserId> {
        match self.revision {
            0 => None,
            _ => self.revisions.get(self.revision.saturating_sub(1))?.editor,
        }
    }

    /// Returns the current version of this message.
    ///
    /// Version 0 is the original message, version 1 is the first revision, etc.
    #[must_use]
    pub const fn revision(&self) -> usize {
        self.revision
    }

    /// Undoes an edit by cycling to the previous revision.
    ///
    /// If already at the original message, cycles to the last revision.
    pub const fn undo(&mut self) {
        self.revision = self
            .revision
            .saturating_add(self.revisions_count())
            .strict_rem(self.revisions_count().saturating_add(1));
    }

    /// Redoes an edit by cycling to the next revision.
    ///
    /// If already at the last revision, cycles to the original message.
    pub const fn redo(&mut self) {
        self.revision = self
            .revision
            .saturating_add(1)
            .strict_rem(self.revisions_count().saturating_add(1));
    }

    /// Returns the time it took for this message to generate, if it originates from an LLM.
    #[must_use]
    pub const fn time_taken(&self) -> Option<Duration> {
        self.elapsed
    }

    /// Converts this message into a vector of Rig messages for the LLM.
    #[must_use]
    pub fn to_rig_messages(&self) -> Vec<RigMessage> {
        let chosen = self.chosen_revision();
        let last_user = chosen.0.iter().rposition(|part| matches!(part.role, Role::User));

        chosen
            .0
            .iter()
            .enumerate()
            .map(|(index, part)| match part.role {
                Role::System => RigMessage::System {
                    content: part.content.clone(),
                },
                Role::Assistant => RigMessage::Assistant {
                    id: None,
                    content: OneOrMany::one(AssistantContent::Text(Text {
                        text: part.content.clone(),
                    })),
                },
                Role::User => {
                    let mut content = OneOrMany::one(UserContent::text(&part.content));

                    if Some(index) == last_user {
                        for url in &self.attachments {
                            if url.contains(PROBABLE_DISCORD_VOICE_RECORDING) {
                                content.push(UserContent::audio_url(url, None));
                            } else {
                                content.push(UserContent::image_url(url, None, None));
                            }
                        }
                    }

                    RigMessage::User { content }
                }
            })
            .collect()
    }
}

impl Parts {
    /// Returns the first (head) part of the message.
    #[must_use]
    pub const fn head(&self) -> &Part {
        &self.0.head
    }

}

impl Part {
    /// Returns the content of this part.
    #[must_use]
    pub fn content(&self) -> &str {
        &self.content
    }
}

impl From<(Character, String, Duration)> for Message {
    fn from((character, response, time_taken): (Character, String, Duration)) -> Self {
        Self::builder()
            .parts((character.name().to_owned(), response, Role::Assistant))
            .elapsed(time_taken)
            .build()
    }
}

/// Splits `text` into one [`Part`] per line, taking each line's role from its
/// `name: ` prefix (`ai` maps to assistant, `system` to system, anything else to
/// the user), or attributing the whole line to `author` when it has no prefix.
/// Every line is [`Role::Assistant`] when `from_bot` is set.
fn parts_from_lines(text: &str, author: &str, from_bot: bool) -> Vec<Part> {
    text.lines()
        .map(|line| {
            let (name, content) = if let Some((name, _)) = line.split_once(": ") {
                (name.to_owned(), line.to_owned())
            } else {
                (author.to_owned(), format!("{author}: {line}"))
            };
            let role = if from_bot || name.eq_ignore_ascii_case("ai") {
                Role::Assistant
            } else if name.eq_ignore_ascii_case("system") {
                Role::System
            } else {
                Role::User
            };
            Part::builder()
                .name(name)
                .content(content)
                .role(role)
                .build()
        })
        .collect()
}

impl From<(&DiscordMessage, String)> for Message {
    fn from((message, author): (&DiscordMessage, String)) -> Self {
        Self::builder()
            .id(message.id)
            .parts(parts_from_lines(
                &message.content,
                &author,
                message.author.bot(),
            ))
            .attachments(&message.attachments)
            .build()
    }
}

impl From<Vec<Part>> for Parts {
    fn from(parts: Vec<Part>) -> Self {
        let Some(nonempty) = NonEmpty::from_vec(parts) else {
            warn!("constructed Parts from an empty list of parts, substituting a blank part");
            return Self(NonEmpty::default());
        };
        Self(nonempty)
    }
}

impl From<(String, String, Role)> for Parts {
    fn from((name, content, role): (String, String, Role)) -> Self {
        Self(NonEmpty::new(
            Part::builder()
                .name(name)
                .content(content)
                .role(role)
                .build(),
        ))
    }
}

/// Tests for message revision navigation and conversion.
#[cfg(test)]
mod tests {
    use super::{Message, Part, Parts, Role, parts_from_lines};
    use rig::message::Message as RigMessage;

    /// Builds a system message edited twice, leaving two revisions on top of the original.
    fn message_with_two_edits() -> Message {
        let mut message = Message::new_system("original");
        message.edit("Bot", "first", None::<u64>);
        message.edit("Bot", "second", None::<u64>);
        message
    }

    /// Editing records each revision and leaves the cursor on the newest one.
    #[test]
    fn edits_advance_to_the_newest_revision() {
        let message = message_with_two_edits();
        assert_eq!(
            message.revisions_count(),
            2,
            "two edits create two revisions"
        );
        assert_eq!(
            message.revision(),
            2,
            "editing moves the cursor to the newest revision"
        );
        assert_eq!(
            message.chosen_revision().head().content(),
            "second",
            "the newest revision holds the latest content"
        );
    }

    /// `undo` cycles backward through revisions and wraps to the newest at the original.
    #[test]
    fn undo_cycles_backward_and_wraps() {
        let mut message = message_with_two_edits();
        message.undo();
        assert_eq!(message.revision(), 1, "undo steps back one revision");
        assert_eq!(
            message.chosen_revision().head().content(),
            "first",
            "revision one holds the first edit"
        );
        message.undo();
        assert_eq!(message.revision(), 0, "undo reaches the original message");
        assert_eq!(
            message.chosen_revision().head().content(),
            "original",
            "revision zero holds the original content"
        );
        message.undo();
        assert_eq!(
            message.revision(),
            2,
            "undo from the original wraps to the newest revision"
        );
    }

    /// `redo` cycles forward through revisions and wraps to the original at the newest.
    #[test]
    fn redo_cycles_forward_and_wraps() {
        let mut message = message_with_two_edits();
        message.redo();
        assert_eq!(
            message.revision(),
            0,
            "redo from the newest revision wraps to the original"
        );
        message.redo();
        assert_eq!(message.revision(), 1, "redo steps forward one revision");
        message.redo();
        assert_eq!(message.revision(), 2, "redo reaches the newest revision");
    }

    /// Each part's role maps to the matching rig message variant.
    #[test]
    fn rig_messages_map_each_part_role() {
        let message = Message::builder()
            .parts(vec![
                Part::builder()
                    .name("System".to_owned())
                    .content("sys".to_owned())
                    .role(Role::System)
                    .build(),
                Part::builder()
                    .name("Bot".to_owned())
                    .content("reply".to_owned())
                    .role(Role::Assistant)
                    .build(),
                Part::builder()
                    .name("Alice".to_owned())
                    .content("hi".to_owned())
                    .role(Role::User)
                    .build(),
            ])
            .build();
        let rig_messages = message.to_rig_messages();
        assert_eq!(rig_messages.len(), 3, "each part maps to one rig message");
        assert!(
            matches!(rig_messages.first(), Some(RigMessage::System { .. })),
            "a system part maps to a system message"
        );
        assert!(
            matches!(rig_messages.get(1), Some(RigMessage::Assistant { .. })),
            "an assistant part maps to an assistant message"
        );
        assert!(
            matches!(rig_messages.get(2), Some(RigMessage::User { .. })),
            "a user part maps to a user message"
        );
    }

    /// A single-part conversion keeps the content, while an empty list falls back to a blank part.
    #[test]
    fn parts_conversions_preserve_content_or_blank() {
        let single: Parts = ("Alice".to_owned(), "hi".to_owned(), Role::User).into();
        assert_eq!(
            single.head().content(),
            "hi",
            "a single-part conversion keeps the content"
        );

        let empty: Parts = Vec::<Part>::new().into();
        assert!(
            empty.head().content().is_empty(),
            "an empty part list falls back to a blank part"
        );
    }

    /// A prefixed line keeps its whole text as content and reads its role from the prefix.
    #[test]
    fn prefixed_lines_take_their_role_from_the_name() {
        let parts = parts_from_lines("system: be terse\nai: sure\nAlice: hi", "Bob", false);
        assert_eq!(parts.len(), 3, "one part per line");

        let first = parts.first();
        assert_eq!(
            first.map(|part| part.name.as_str()),
            Some("system"),
            "the prefix becomes the name"
        );
        assert_eq!(
            first.map(|part| part.content.as_str()),
            Some("system: be terse"),
            "the whole prefixed line is kept as content"
        );
        assert!(
            matches!(first.map(|part| part.role), Some(Role::System)),
            "a system prefix maps to the system role"
        );
        assert!(
            matches!(parts.get(1).map(|part| part.role), Some(Role::Assistant)),
            "an ai prefix maps to the assistant role"
        );
        assert!(
            matches!(parts.get(2).map(|part| part.role), Some(Role::User)),
            "any other prefix maps to the user role"
        );
    }

    /// An unprefixed line is attributed to the author and prefixed with their name.
    #[test]
    fn unprefixed_lines_are_attributed_to_the_author() {
        let parts = parts_from_lines("hello", "Bob", false);
        assert_eq!(parts.len(), 1, "a single line yields a single part");

        let first = parts.first();
        assert_eq!(
            first.map(|part| part.name.as_str()),
            Some("Bob"),
            "the author becomes the name"
        );
        assert_eq!(
            first.map(|part| part.content.as_str()),
            Some("Bob: hello"),
            "the author name is prefixed onto the content"
        );
        assert!(
            matches!(first.map(|part| part.role), Some(Role::User)),
            "an author line defaults to the user role"
        );
    }

    /// A bot author forces every line to the assistant role regardless of any prefix.
    #[test]
    fn bot_author_forces_the_assistant_role() {
        let parts = parts_from_lines("system: still assistant\nplain line", "Harry", true);
        assert!(
            parts.iter().all(|part| matches!(part.role, Role::Assistant)),
            "every line from a bot author is an assistant part"
        );
    }

    /// A mid-line ": " is still parsed as a prefix, splitting name from the kept content.
    #[test]
    fn a_mid_line_colon_is_parsed_as_a_prefix() {
        let parts = parts_from_lines("I said: hi", "Bob", false);
        assert_eq!(parts.len(), 1, "a single line yields a single part");

        let first = parts.first();
        assert_eq!(
            first.map(|part| part.name.as_str()),
            Some("I said"),
            "the text before the first colon-space becomes the name"
        );
        assert_eq!(
            first.map(|part| part.content.as_str()),
            Some("I said: hi"),
            "the whole line is still kept as content"
        );
        assert!(
            matches!(first.map(|part| part.role), Some(Role::User)),
            "an unrecognized prefix defaults to the user role"
        );
    }
}
