[package]
name = "ultimate_harry"
version = "0.0.4"
edition = "2024"

[dependencies]
poise = "0.6.1"
tokio = { version = "1.44.1", features = ["rt-multi-thread"] }
ulid = "1.2.1"
ultimate_character = { path = "../ultimate_character" }
ultimate_message = { path = "../ultimate_message" }
ultimate_config = { path = "../ultimate_config" }
ultimate_statistics = { path = "../ultimate_statistics" }
ultimate_phrases = { path = "../ultimate_phrases" }
ultimate_modals = { path = "../ultimate_modals" }
ultimate_history = { path = "../ultimate_history" }
nanorand = "0.7.0"
snafu = "0.8.5"
tracing = "0.1.41"
miette = "7.5.0"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
missing-errors-doc = "allow"                 # TODO: remove
enum_glob_use = "deny"
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
